[build]
  command = "npm run pages:build"
  publish = ".vercel/output/static"

[compatibility]
  compatibility_date = "2024-02-08"
  flags = ["nodejs_compat"]

[vars]
# You will set these in the Cloudflare Dashboard
# NEXT_PUBLIC_SUPABASE_URL = "..."
# NEXT_PUBLIC_SUPABASE_ANON_KEY = "..."

[site]
  bucket = ".vercel/output/static"

